# Build settings
markdown: kramdown

# Site settings
description: "ASP.NET Developer, Code Club Volunteer and STEM Ambassador."
github_username:  Y90SMH
title: "Sean Holcroft"
url: "https://seanholcroft.co.uk"